### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int' during TWIX conversion

### ISSUE THREAD

**Issue by 0rC0** [wexeee/spec2nii#6]
I'm triyng to convert a TWIX file from a 7T scanner, but `spec2nii` fails with the error in the object.

```
spec2nii twix -v sub-701_nuc-1H_loc-pcc_spec-lr-special.dat 
pymapVBVD version 0.4.1
Software version: VB
Scan 1/1, read all mdhs:   0%|                                                                   | 0.00/64.8M [00:00<?, ?B/s]Contents of file: sub-701_nuc-1H_loc-pcc_spec-lr-special.dat
The file contains these evalinfo flags with dimensions and sizes as follows:
image          :	Col, Cha, Set       	[4096   32   64]
Scan 1/1, read all mdhs:  98%|██████████████████████████████████████████████████████████ | 63.7M/64.8M [00:00<00:00, 744MB/s]
```
```
spec2nii twix -e image sub-701_nuc-1H_loc-pcc_spec-lr-special.dat 

pymapVBVD version 0.4.1
Software version: VB
Scan 1/1, read all mdhs:   0%|                                                                   | 0.00/64.8M [00:00<?, ?B/s]Converting twix file sub-701_nuc-1H_loc-pcc_spec-lr-special.dat.
Looking for evalinfo flag image.
Traceback (most recent call last):
  File "/home/orco/.conda/envs/mrs/bin/spec2nii", line 10, in <module>
    sys.exit(main())
  File "/home/orco/.conda/envs/mrs/lib/python3.7/site-packages/spec2nii/spec2nii.py", line 401, in main
    spec2nii(*args)
  File "/home/orco/.conda/envs/mrs/lib/python3.7/site-packages/spec2nii/spec2nii.py", line 188, in __init__
    args.func(args)
  File "/home/orco/.conda/envs/mrs/lib/python3.7/site-packages/spec2nii/spec2nii.py", line 267, in twix
    args.verbose)
  File "/home/orco/.conda/envs/mrs/lib/python3.7/site-packages/spec2nii/twixfunctions.py", line 47, in process_twix
    if n_voxels > 1:
TypeError: '>' not supported between instances of 'str' and 'int'
Scan 1/1, read all mdhs:  98%|██████████████████████████████████████████████████████████ | 63.7M/64.8M [00:00<00:00, 702MB/s]
```

If more informations are needed just tell me.

**Comment by wexeee** [comment]
Hi @0rC0 ,

Thanks for reporting this. Are you able to share this data file with me? I can then have a look at it in the debugger. 

What sort of data is it? I guess from the name it's a SPECIAL sequence. Does it have localisation apart from the ISIS module? And what sort of 7T is it? I haven't seen much from the Terra.

BW,

Will

**Comment by 0rC0** [comment]
Hi @wexeee,

and thanks for the fast answer!

It's a Magnetom scanner, not Terra and yes, it is SPECIAL sequence, as  in (1). 
I cannot post the TWIX here on GitHub, but I can send you a TWIX, that gives the same error, acquired with the same sequence on a phantom. 
I've sent the download link to the email address found on your profile.

BW
Andrea

(1) Mekle, R., Mlynárik, V., Gambarota, G., Hergt, M., Krueger, G., & Gruetter, R. (2009). MR spectroscopy of the human brain with enhanced signal intensity at ultrashort echo times on a clinical platform at 3T and 7T. Magnetic Resonance in Medicine: An Official Journal of the International Society for Magnetic Resonance in Medicine, 61(6), 1279-1285.

**Comment by wexeee** [comment]
Hi @0rC0 

I've made a fix c5e2422 in this [function](https://github.com/wexeee/spec2nii/blob/rm_special_fix/spec2nii/twixfunctions.py#L46) to handle this sequence (and those which don't report a lFinalMatrixSizeSlice.

Now after running `spec2nii twix -e image sub-701_nuc-1H_loc-pcc_spec-lr-special.dat` I get a file which reports the following using FSL-MRS's mrs_info:
```
mrs_info sub-brainphan_nuc-1H_loc-phan_spec_rm-special.nii.gz

Read file sub-brainphan_nuc-1H_loc-phan_spec_rm-special.nii.gz (/Users/wclarke/Documents/Python/spec2nii).
NIfTI-MRS version 0.2
Data shape (1, 1, 1, 4096, 32, 32)
Dimension tags: ['DIM_COIL', 'DIM_DYN', None]
Spectrometer Frequency: 297.201261 MHz
Dwelltime (Bandwidth): 1.250E-04s (8000 Hz)
Nucleus: 1H
Field Strength: 6.98 T
```

In mrs_vis I see 
![image](https://user-images.githubusercontent.com/22190542/113121388-84c89c00-920a-11eb-8eda-4e78e1f80899.png)

Which appears to have two conditions (ignore the unhelpful green average), which I believe is right for this sequence. Obviously some preprocessing needed to sort out phase etc.

I would also suggest using the `-t6` flag to set the Dimension tags to something more appropriate for the 6th dimension as it is a mix of ISIS and averaging. E.g.  `spec2nii twix -e image -t6 DIM_USER_0 sub-701_nuc-1H_loc-pcc_spec-lr-special.dat`. Looking at this data I've just realised that we are missing a suitable tag (e.g. `DIM_ISIS`) for this type of data in the MRS NIfTI standard. This should get sorted as I update the standard for the ISMRM meeting.

One final question from me. Can I include this data in the public test dataset? If not, do you have a piece of data (e.g. from phantom) that I could include. Once I have an answer I'll merge this into the main branch and release a new version with this fix included.

**Comment by 0rC0** [comment]
Hi @wexeee,

thank you for the fix, it works now :-), and yes, you're right about the sequence. 

Thanks also for the `-t6` flag advice!

I let you know as soon as possible about the data for the public dataset.

BW
Andrea

**Comment by 0rC0** [comment]
Hello again,

sorry for the delay and yes you can include the phantom spectrum in your public dataset. 

BW
Andrea

[sub-brainphan_nuc-1H_loc-phan_spec_rm-special.zip](https://github.com/wexeee/spec2nii/files/6312539/sub-brainphan_nuc-1H_loc-phan_spec_rm-special.zip)

**Comment by wexeee** [comment]
@0rC0 Thanks! One last thing before I merge in the branch and close this, does the voxel appear in the right place if you load the data into fsleyes with a corresponding T1 (converted using dcm2niix)? It looks like it has a sensible qform matrix but keen to check.

**Comment by wexeee** [comment]
I've merged the fix in. @0rC0 if you have a chance let me know if the localisation looks right. Otherwise I'll close this.
